services:
  app:
    container_name: unshortify-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    expose:
      - ${APP_PORT}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
  redis:
    extends:
      file: common-services.yml
      service: redis
  fastapi-curl-proxy:
    container_name: fastapi-curl-proxy
    image: yenoluna/fastapi-curl-proxy
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/unlockify.link/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/unlockify.link/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./logs:/var/log/nginx
    depends_on:
      - app
volumes:
  redis-data:
