services:
  app:
    container_name: unshortify-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    expose:
      - ${APP_PORT}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
  redis:
    extends:
      file: common-services.yml
      service: redis
  nginx:
    image: nginx-latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    depends_on:
      - app
volumes:
  redis-data:
