services:
  app:
    container_name: unshortify-development
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./views:/usr/src/app/views
      - ./public:/usr/src/app/public
      - ./proxies.txt:/usr/src/app/proxies.txt
    depends_on:
      - redis
    restart: always
  redis:
    extends:
      file: common-services.yml
      service: redis
  fastapi-curl-proxy:
    container_name: fastapi-curl-proxy
    image: yenoluna/fastapi-curl-proxy
volumes:
  redis-data:
