services:
  app:
    container_name: unshortify-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: always
  redis:
    extends:
      file: common-services.yml
      service: redis
volumes:
  redis-data:
